'use client';

import React, { useEffect, useState, FormEvent } from 'react';
import clsx from 'clsx';
import { supabase } from '../utils/supabaseClient';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import { useQueryClient } from '@tanstack/react-query';

type InvoiceStatus = 'draft' | 'sent' | 'paid' | 'overdue';

export type Invoice = {
  id: number;
  business_id?: string | null;
  invoice_number: string;
  client_name: string;
  issue_date: string | null;
  due_date: string | null;
  status: InvoiceStatus;
  subtotal: number;
  tax: number | null;
  total: number;
  notes?: string | null;
  created_at: string;
  transaction_id?: number | null;
};

type InvoiceForPrint = Invoice & {
  items?: InvoiceItem[];
  businessName?: string | null;
};

function InvoicePrintView({ invoice }: { invoice: InvoiceForPrint }) {
  const businessName = invoice.businessName || 'RevGuard';
  const footerText = `Generated by ${businessName}`;
  const subtotal = Number(invoice.subtotal || 0);
  const tax = Number(invoice.tax || 0);
  const total = Number(invoice.total || 0);

  return (
    <div
      style={{
        width: '800px',
        minHeight: '1040px', // approx A4 height in px
        padding: '32px',
        backgroundColor: '#ffffff',
        color: '#111827',
        fontFamily:
          "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
        fontSize: '12px',
        display: 'flex',
        flexDirection: 'column',
      }}
    >
      <div>
        {/* Header */}
        <div
          style={{
            display: 'flex',
            justifyContent: 'space-between',
            marginBottom: '24px',
            borderBottom: '2px solid #e5e7eb',
            paddingBottom: '12px',
          }}
        >
          <div>
            <div
              style={{
                fontSize: '22px',
                fontWeight: 700,
                marginBottom: '4px',
              }}
            >
              {businessName}
            </div>
            <div style={{ fontSize: '11px', color: '#4b5563' }}>
              AI-Powered Financial Clarity
            </div>
          </div>
          <div
            style={{
              textAlign: 'right',
              fontSize: '11px',
              color: '#4b5563',
            }}
          >
            <div>revguard.io</div>
            <div>support@revguard.io</div>
          </div>
        </div>

        {/* Title + basic invoice info */}
        <div
          style={{
            display: 'flex',
            justifyContent: 'space-between',
            marginBottom: '20px',
          }}
        >
          <div>
            <div
              style={{
                fontSize: '18px',
                fontWeight: 700,
                marginBottom: '4px',
              }}
            >
              Invoice #{invoice.invoice_number}
            </div>
            <div style={{ fontSize: '11px', color: '#4b5563' }}>
              Status:{' '}
              <span style={{ fontWeight: 600, textTransform: 'capitalize' }}>
                {invoice.status}
              </span>
            </div>
          </div>

          <div
            style={{
              fontSize: '11px',
              textAlign: 'right',
              color: '#4b5563',
            }}
          >
            <div>
              <span style={{ fontWeight: 600 }}>Issue date: </span>
              {invoice.issue_date}
            </div>
            <div>
              <span style={{ fontWeight: 600 }}>Due date: </span>
              {invoice.due_date}
            </div>
          </div>
        </div>

        {/* Client / Billing block */}
        <div
          style={{
            display: 'flex',
            justifyContent: 'space-between',
            marginBottom: '24px',
          }}
        >
          <div style={{ flex: 1, marginRight: '16px' }}>
            <div
              style={{
                fontSize: '12px',
                fontWeight: 600,
                marginBottom: '4px',
              }}
            >
              Bill To
            </div>
            <div style={{ fontSize: '11px' }}>{invoice.client_name}</div>
            {/* Add client address/contact here later if you store it */}
          </div>

          <div style={{ flex: 1, textAlign: 'right' }}>
            <div
              style={{
                fontSize: '12px',
                fontWeight: 600,
                marginBottom: '4px',
              }}
            >
              From
            </div>
            <div style={{ fontSize: '11px' }}>{businessName}</div>
            {/* Replace with your real business name/address when ready */}
          </div>
        </div>

        {/* Items table */}
        <table
          style={{
            width: '100%',
            borderCollapse: 'collapse',
            marginBottom: '16px',
          }}
        >
          <thead>
            <tr>
              <th
                style={{
                  borderBottom: '1px solid #d1d5db',
                  textAlign: 'left',
                  padding: '8px 4px',
                  backgroundColor: '#f9fafb',
                  fontSize: '11px',
                }}
              >
                Description
              </th>
              <th
                style={{
                  borderBottom: '1px solid #d1d5db',
                  textAlign: 'right',
                  padding: '8px 4px',
                  backgroundColor: '#f9fafb',
                  fontSize: '11px',
                }}
              >
                Qty
              </th>
              <th
                style={{
                  borderBottom: '1px solid #d1d5db',
                  textAlign: 'right',
                  padding: '8px 4px',
                  backgroundColor: '#f9fafb',
                  fontSize: '11px',
                }}
              >
                Unit price
              </th>
              <th
                style={{
                  borderBottom: '1px solid #d1d5db',
                  textAlign: 'right',
                  padding: '8px 4px',
                  backgroundColor: '#f9fafb',
                  fontSize: '11px',
                }}
              >
                Line total
              </th>
            </tr>
          </thead>
          <tbody>
            {(invoice.items || []).map((it, idx) => {
              const qty = it.quantity ?? 0;
              const price = it.unit_price ?? 0;
              const line = qty * price;

              return (
                <tr key={idx}>
                  <td
                    style={{
                      borderBottom: '1px solid #e5e7eb',
                      padding: '6px 4px',
                      fontSize: '11px',
                    }}
                  >
                    {it.description}
                  </td>
                  <td
                    style={{
                      borderBottom: '1px solid #e5e7eb',
                      padding: '6px 4px',
                      textAlign: 'right',
                      fontSize: '11px',
                    }}
                  >
                    {qty}
                  </td>
                  <td
                    style={{
                      borderBottom: '1px solid #e5e7eb',
                      padding: '6px 4px',
                      textAlign: 'right',
                      fontSize: '11px',
                    }}
                  >
                    ${price.toFixed(2)}
                  </td>
                  <td
                    style={{
                      borderBottom: '1px solid #e5e7eb',
                      padding: '6px 4px',
                      textAlign: 'right',
                      fontSize: '11px',
                    }}
                  >
                    ${line.toFixed(2)}
                  </td>
                </tr>
              );
            })}

            {(!invoice.items || invoice.items.length === 0) && (
              <tr>
                <td
                  colSpan={4}
                  style={{
                    padding: '10px 4px',
                    fontSize: '11px',
                    color: '#6b7280',
                    textAlign: 'center',
                  }}
                >
                  No line items.
                </td>
              </tr>
            )}
          </tbody>
        </table>

        {/* Totals block */}
        <div
          style={{
            width: '260px',
            marginLeft: 'auto',
            border: '1px solid #e5e7eb',
            borderRadius: '4px',
            padding: '10px 12px',
            fontSize: '11px',
          }}
        >
          <div
            style={{
              display: 'flex',
              justifyContent: 'space-between',
              marginBottom: '4px',
            }}
          >
            <span>Subtotal</span>
            <span>${subtotal.toFixed(2)}</span>
          </div>
          <div
            style={{
              display: 'flex',
              justifyContent: 'space-between',
              marginBottom: '4px',
            }}
          >
            <span>Tax</span>
            <span>${tax.toFixed(2)}</span>
          </div>
          <div
            style={{
              borderTop: '1px solid #e5e7eb',
              marginTop: '6px',
              paddingTop: '6px',
              display: 'flex',
              justifyContent: 'space-between',
              fontWeight: 700,
            }}
          >
            <span>Total</span>
            <span>${total.toFixed(2)}</span>
          </div>
        </div>

        {/* Notes */}
        {invoice.notes && (
          <div style={{ marginTop: '18px', fontSize: '11px' }}>
            <div style={{ fontWeight: 600, marginBottom: '4px' }}>Notes</div>
            <p>{invoice.notes}</p>
          </div>
        )}
      </div>

      {/* Footer pinned to bottom */}
      <div
        style={{
          marginTop: 'auto',
          fontSize: '10px',
          color: '#6b7280',
          textAlign: 'center',
          paddingTop: '12px',
          borderTop: '1px solid #e5e7eb',
        }}
      >
        {footerText}
      </div>
    </div>
  );
}

type InvoiceItem = {
  id?: number;
  invoice_id?: number;
  description: string;
  quantity: number | null;
  unit_price: number | null;
  line_total?: number;
};

type InvoiceTabProps = {
  businessId: string | null;
  businessName?: string | null;
  /** Provided by shared app cache so this tab doesn't fetch on mount. */
  invoices?: Invoice[];
  /** Provided by shared app cache so this tab doesn't fetch supabase auth on mount. */
  userId?: string | null;
  loading?: boolean;
  error?: string | null;
};

const todayISO = () => new Date().toISOString().slice(0, 10);

const emptyInvoice = (businessId: string | null): Partial<Invoice> => ({
  business_id: businessId,
  invoice_number: '',
  client_name: '',
  issue_date: null,
  due_date: null,
  status: 'draft',
  subtotal: 0,
  tax: null,
  total: 0,
  notes: '',
});

const emptyItem = (): InvoiceItem => ({
  description: '',
  quantity: null,
  unit_price: null,
});

function daysBetween(from: string, to: string) {
  const a = new Date(from);
  const b = new Date(to);
  const diffMs = b.getTime() - a.getTime();
  return Math.round(diffMs / (1000 * 60 * 60 * 24));
}

const InvoiceTab: React.FC<InvoiceTabProps> = ({
  businessId,
  businessName,
  invoices: invoicesProp,
  userId: userIdProp,
  loading: loadingProp,
  error: errorProp,
}) => {
  const queryClient = useQueryClient();
  const invoices = invoicesProp ?? [];
  const loading = Boolean(loadingProp);
  const [error, setError] = useState<string | null>(null);
  const userId = userIdProp ?? null;
  const [resolvedBusinessId, setResolvedBusinessId] = useState<string | null>(
    businessId ?? null
  );

  const [showForm, setShowForm] = useState(false);
  const [saving, setSaving] = useState(false);
  const [newInvoice, setNewInvoice] = useState<Partial<Invoice>>(
    emptyInvoice(businessId)
  );
  const [items, setItems] = useState<InvoiceItem[]>([emptyItem(), emptyItem()]);
  const [invoiceItemsById, setInvoiceItemsById] = useState<
    Record<number, InvoiceItem[]>
  >({});
  const [markingId, setMarkingId] = useState<number | null>(null);
  const [editingInvoiceId, setEditingInvoiceId] = useState<number | null>(null);
  const [openNotesInvoiceId, setOpenNotesInvoiceId] = useState<number | null>(
    null
  );

  const effectiveError = error || errorProp;

  useEffect(() => {
    // Keep a stable "effective business id" even if the parent is still loading it.
    if (businessId) setResolvedBusinessId(businessId);
  }, [businessId]);

  async function requireBusinessIdForSessionUser(): Promise<{ userId: string; businessId: string }> {
    const { data: sess } = await supabase.auth.getSession();
    const user = sess.session?.user ?? null;

    // eslint-disable-next-line no-console
    console.log('invoice insert user.id', user?.id ?? null);

    if (!user?.id) {
      throw new Error('AUTH_REQUIRED');
    }

    if (resolvedBusinessId) {
      return { userId: user.id, businessId: resolvedBusinessId };
    }

    const { data: biz, error: bizErr } = await supabase
      .from('business')
      .select('id')
      .eq('owner_id', user.id)
      .order('created_at', { ascending: true })
      .limit(1)
      .single();

    if (bizErr || !biz?.id) {
      throw new Error('No business found for user');
    }

    const id = String((biz as any).id);
    setResolvedBusinessId(id);
    return { userId: user.id, businessId: id };
  }

  // Resolve business id ASAP so buttons can enable without relying on parent state.
  useEffect(() => {
    let alive = true;
    if (!resolvedBusinessId && userId) {
      void (async () => {
        try {
          const r = await requireBusinessIdForSessionUser();
          if (!alive) return;
          setResolvedBusinessId(r.businessId);
        } catch {
          // ignore; UI will show "Select or create business"
        }
      })();
    }
    return () => {
      alive = false;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [userId, resolvedBusinessId]);

  // Recalculate subtotal/tax/total from line items (tax is a flat dollar amount)
  const recalcTotalsFromItems = (draftItems: InvoiceItem[], taxValue?: number) => {
    const subtotal = draftItems.reduce((sum, item) => {
      const qty = item.quantity ?? 0;
      const price = item.unit_price ?? 0;
      return sum + qty * price;
    }, 0);

    const tax =
      typeof taxValue === 'number'
        ? taxValue
        : Number(newInvoice.tax || 0);

    const total = subtotal + tax;

    setNewInvoice((prev) => ({
      ...prev,
      subtotal,
      tax,
      total,
    }));
  };

  const handleInvoiceFieldChange = (
    field: keyof Invoice,
    value: string | number
  ) => {
    const updated: Partial<Invoice> = { ...newInvoice, [field]: value };
    setNewInvoice(updated);
  };

  // Handle line item changes
  const handleItemChange = (
    index: number,
    field: keyof InvoiceItem,
    value: string | number | null
  ) => {
    const draft = [...items];
    const item: InvoiceItem = { ...draft[index] };

    if (field === 'description') {
      item.description = String(value);
    }

    if (field === 'quantity') {
      const n = value as number | null;
      item.quantity = n === null || Number.isNaN(n) ? null : n;
    }

    if (field === 'unit_price') {
      const n = value as number | null;
      item.unit_price = n === null || Number.isNaN(n) ? null : n;
    }

    draft[index] = item;
    setItems(draft);
    recalcTotalsFromItems(draft);
  };

  const addItemRow = () => {
    setItems((prev) => [...prev, emptyItem()]);
  };

  const removeItemRow = (index: number) => {
    setItems((prev) => {
      const draft = [...prev];
      draft.splice(index, 1);
      const safeDraft = draft.length === 0 ? [emptyItem()] : draft;
      recalcTotalsFromItems(safeDraft);
      return safeDraft;
    });
  };

  const handleSaveInvoice = async (e: FormEvent) => {
    e.preventDefault();
    let businessIdToUse: string;
    try {
      const r = await requireBusinessIdForSessionUser();
      businessIdToUse = r.businessId;
    } catch (err: any) {
      setError(err?.message ?? 'No business found for user');
      return;
    }

    setSaving(true);
    setError(null);

    const today = todayISO();

    const basePayload = {
      invoice_number: newInvoice.invoice_number || '',
      client_name: newInvoice.client_name || '',
      issue_date: newInvoice.issue_date || today,
      due_date: newInvoice.due_date || today,
      status: (newInvoice.status || 'draft') as InvoiceStatus,
      subtotal: Number(newInvoice.subtotal || 0),
      tax: Number(newInvoice.tax || 0),
      total: Number(newInvoice.total || 0),
      notes: newInvoice.notes || null,
      business_id: businessIdToUse,
    };

    try {
      if (editingInvoiceId) {
        // UPDATE existing invoice
        const {
          data: updated,
          error: invError,
        } = await supabase
          .from('invoices')
          .update(basePayload)
          .eq('id', editingInvoiceId)
          .eq('business_id', businessIdToUse)
          .select('*')
          .single();

        if (invError || !updated) {
          // eslint-disable-next-line no-console
          console.error('Error updating invoice', invError);
          setError(invError?.message || 'Could not update invoice');
          return;
        }

        // Replace invoice_items: delete then reinsert
        const { error: delError } = await supabase
          .from('invoice_items')
          .delete()
          .eq('invoice_id', editingInvoiceId);
        if (delError) {
          // eslint-disable-next-line no-console
          console.error('Error clearing invoice items', delError);
        }

        const itemsToInsert = items
          .filter(
            (it) =>
              it.description.trim() &&
              it.quantity !== null &&
              it.unit_price !== null
          )
          .map((it) => ({
            invoice_id: editingInvoiceId,
            description: it.description.trim(),
            quantity: it.quantity,
            unit_price: it.unit_price,
            line_total: (it.quantity ?? 0) * (it.unit_price ?? 0),
          }));

        if (itemsToInsert.length > 0) {
          const { error: itemsError } = await supabase
            .from('invoice_items')
            .insert(itemsToInsert);
          if (itemsError) {
            // eslint-disable-next-line no-console
            console.error('Error updating invoice items', itemsError);
          }
        }

        await queryClient.invalidateQueries({ queryKey: ['invoices', businessIdToUse] });
      } else {
        // CREATE new invoice
        const payload = { ...basePayload, business_id: businessIdToUse };
        // eslint-disable-next-line no-console
        console.log('invoice insert payload', payload);
        const {
          data: inserted,
          error: invError,
        } = await supabase
          .from('invoices')
          .insert(payload)
          .select('*')
          .single();

        if (invError || !inserted) {
          // eslint-disable-next-line no-console
          console.error('Error creating invoice', invError);
          setError(invError?.message || 'Could not create invoice');
          return;
        }

        const created = inserted as Invoice;

        const itemsToInsert = items
          .filter(
            (it) =>
              it.description.trim() &&
              it.quantity !== null &&
              it.unit_price !== null
          )
          .map((it) => ({
            invoice_id: created.id,
            description: it.description.trim(),
            quantity: it.quantity,
            unit_price: it.unit_price,
            line_total: (it.quantity ?? 0) * (it.unit_price ?? 0),
          }));

        if (itemsToInsert.length > 0) {
          const { error: itemsError } = await supabase
            .from('invoice_items')
            .insert(itemsToInsert);
          if (itemsError) {
            // eslint-disable-next-line no-console
            console.error('Error creating invoice items', itemsError);
          }
        }

        await queryClient.invalidateQueries({ queryKey: ['invoices', businessIdToUse] });
      }

      // Reset form after save
      setEditingInvoiceId(null);
      setShowForm(false);
      setNewInvoice(emptyInvoice(businessIdToUse));
      setItems([emptyItem(), emptyItem()]);
    } finally {
      setSaving(false);
    }
  };

  const beginEditInvoice = async (inv: Invoice) => {
    setError(null);
    setEditingInvoiceId(inv.id);

    const { data: itemData, error: itemError } = await supabase
      .from('invoice_items')
      .select('id, description, quantity, unit_price, line_total')
      .eq('invoice_id', inv.id)
      .order('id', { ascending: true });

    if (itemError) {
      // eslint-disable-next-line no-console
      console.error('Error loading invoice items for edit', itemError);
    }

    const loadedItems: InvoiceItem[] =
      itemData?.map((row: any) => ({
        id: row.id,
        invoice_id: inv.id,
        description: row.description || '',
        quantity: row.quantity ?? null,
        unit_price: row.unit_price ?? null,
        line_total: row.line_total ?? null,
      })) ?? [];

    setNewInvoice({
      invoice_number: inv.invoice_number,
      client_name: inv.client_name,
      issue_date: inv.issue_date,
      due_date: inv.due_date,
      status: inv.status as InvoiceStatus,
      subtotal: inv.subtotal,
      tax: inv.tax,
      total: inv.total,
      notes: inv.notes ?? '',
    });

    setItems(loadedItems.length > 0 ? loadedItems : [emptyItem()]);
    setShowForm(true);
  };

  const handleStatusChange = async (
    inv: Invoice,
    nextStatus: InvoiceStatus
  ) => {
    setError(null);
    if (!userId) {
      setError('Please log in to update invoices.');
      return;
    }

    const { data, error: updError } = await supabase
      .from('invoices')
      .update({ status: nextStatus })
      .eq('id', inv.id)
      .eq('business_id', inv.business_id)
      .select('*')
      .single();

    if (updError) {
      setError(updError.message || 'Could not update status.');
      return;
    }

    if (data) {
      const row = data as any;
      const updated: Invoice = {
        id: row.id as number,
        business_id: row.business_id ?? inv.business_id,
        invoice_number: row.invoice_number ?? inv.invoice_number,
        client_name: row.client_name ?? inv.client_name,
        issue_date: row.issue_date ?? inv.issue_date,
        due_date: row.due_date ?? inv.due_date,
        status: (row.status as InvoiceStatus) ?? nextStatus,
        subtotal: Number(row.subtotal ?? inv.subtotal) || 0,
        tax: Number(row.tax ?? inv.tax) || 0,
        total: Number(row.total ?? inv.total) || 0,
        notes: row.notes ?? inv.notes,
        created_at: row.created_at ?? inv.created_at,
        transaction_id: row.transaction_id ?? inv.transaction_id ?? null,
      };

      await queryClient.invalidateQueries({ queryKey: ['invoices', businessId] });

      if (nextStatus === 'draft') {
        await beginEditInvoice(updated);
      }
    }
  };

  const handleMarkPaidAndCreateTx = async (inv: Invoice) => {
    if (!inv) return;

    setError(null);
    setMarkingId(inv.id);

    try {
      if (!userId) {
        setError('Please log in to mark invoices as paid.');
        return;
      }

      // 1) Mark invoice as paid in Supabase
      const { data: updatedInvoice, error: invError } = await supabase
        .from('invoices')
        .update({ status: 'paid' })
        .eq('id', inv.id)
        .eq('business_id', inv.business_id)
        .select('*')
        .single();

      if (invError || !updatedInvoice) {
        // eslint-disable-next-line no-console
        console.error('Error updating invoice status', invError);
        setError(invError?.message || 'Could not mark invoice as paid.');
        return;
      }

      const paidInvoice = updatedInvoice as Invoice;

      // 2) Create matching transaction
      const today = todayISO();

      const txPayload: any = {
        date: today,
        description: `Invoice #${paidInvoice.invoice_number} - ${paidInvoice.client_name}`,
        category: 'Invoice Payment',
        amount: Number(paidInvoice.total || 0),
      };

      if (paidInvoice.business_id) {
        txPayload.business_id = paidInvoice.business_id;
      }

      const { error: txError } = await supabase
        .from('transactions')
        .insert(txPayload);

      if (txError) {
        // eslint-disable-next-line no-console
        console.error('Error creating transaction for paid invoice', txError);
        setError(
          txError.message ||
            'Invoice marked as paid, but failed to create matching transaction.'
        );
      }

      // 3) Refresh cached lists (invoice status + created transaction).
      await queryClient.invalidateQueries({ queryKey: ['invoices', businessId] });
      if (paidInvoice.business_id) {
        await queryClient.invalidateQueries({ queryKey: ['transactions', paidInvoice.business_id] });
      }
    } finally {
      setMarkingId(null);
    }
  };

  const autoStatusLabel = (inv: Invoice) => {
    const today = todayISO();
    const dueDate = inv.due_date ?? today;
    const daysToDue = daysBetween(today, dueDate);

    let displayStatus: InvoiceStatus = inv.status;
    if (inv.status !== 'paid' && inv.status !== 'draft' && inv.due_date) {
      if (inv.due_date < today) {
        displayStatus = 'overdue';
      }
    }

    let subtitle = '';
    if (displayStatus === 'overdue' && inv.status !== 'paid') {
      const daysPast = daysBetween(dueDate, today);
      subtitle = `${daysPast} day${daysPast === 1 ? '' : 's'} past due`;
    } else if (displayStatus === 'sent') {
      if (daysToDue > 0) {
        subtitle = `${daysToDue} day${daysToDue === 1 ? '' : 's'} until due`;
      } else if (daysToDue === 0) {
        subtitle = 'Due today';
      }
    }

    return { displayStatus, subtitle };
  };

  const statusBadgeClass = (status: InvoiceStatus) => {
    switch (status) {
      case 'paid':
        return 'bg-[#2DD4BF]/20 text-[#6EF3C5] border border-[#2DD4BF]/40';
      case 'overdue':
        return 'bg-red-500/20 text-red-400 border border-red-500/40';
      case 'sent':
        return 'bg-blue-500/20 text-blue-400 border border-blue-500/40';
      case 'draft':
      default:
        return 'bg-gray-500/20 text-gray-300 border border-gray-500/40';
    }
  };

  // Outstanding = not paid and not overdue
  const outstandingTotal = invoices
    .filter((i) => i.status !== 'paid' && i.status !== 'overdue')
    .reduce((sum, i) => sum + Number(i.total || 0), 0);

  // Overdue = status explicitly marked as 'overdue'
  const overdueTotal = invoices
    .filter((i) => i.status === 'overdue')
    .reduce((sum, i) => sum + Number(i.total || 0), 0);

  const toggleNotes = (invoiceId: number) => {
    setOpenNotesInvoiceId((current) => (current === invoiceId ? null : invoiceId));
  };

  async function ensureInvoiceItemsLoaded(invoiceId: number) {
    if (invoiceItemsById[invoiceId]) return;

    const { data, error: itemsError } = await supabase
      .from('invoice_items')
      .select('*')
      .eq('invoice_id', invoiceId);

    if (itemsError) {
      setError(itemsError.message || 'Could not load invoice items.');
      return;
    }

    const rows = (data ?? []) as any[];
    const mapped: InvoiceItem[] = rows.map((row) => ({
      id: row.id as number,
      invoice_id: row.invoice_id as number,
      description: row.description ?? '',
      quantity: Number(row.quantity) || 0,
      unit_price: Number(row.unit_price) || 0,
      line_total: Number(row.line_total) || 0,
    }));

    setInvoiceItemsById((prev) => ({
      ...prev,
      [invoiceId]: mapped,
    }));
  }

  async function downloadInvoicePDF(invoice: Invoice) {
    const element = document.getElementById(`invoice-print-${invoice.id}`);
    if (!element) {
      // eslint-disable-next-line no-console
      console.error('No print element found for invoice', invoice.id);
      return;
    }

    try {
      const canvas = await html2canvas(element, {
        scale: 2,
        backgroundColor: '#ffffff',
        logging: false,
        useCORS: true,
        onclone: (doc) => {
          // Strip global stylesheets from the cloned document to avoid
          // unsupported modern color functions (like lab()) used by Tailwind.
          doc
            .querySelectorAll('style,link[rel="stylesheet"]')
            .forEach((el) => el.parentNode?.removeChild(el));
        },
      });

      const imgData = canvas.toDataURL('image/png');
      const pdf = new jsPDF('p', 'mm', 'a4');
      const width = pdf.internal.pageSize.getWidth();
      const height = (canvas.height * width) / canvas.width;

      pdf.addImage(imgData, 'PNG', 0, 0, width, height);
      pdf.save(`invoice-${invoice.invoice_number}.pdf`);
    } catch (err) {
      // eslint-disable-next-line no-console
      console.error('PDF export failed:', err);
      setError('PDF export failed. Please try again.');
    }
  }

  async function handleDownloadInvoice(inv: Invoice) {
    await ensureInvoiceItemsLoaded(inv.id);
    // Wait a tick for React to render the hidden print block with items
    await new Promise<void>((resolve) => {
      requestAnimationFrame(() => resolve());
    });
    await downloadInvoicePDF(inv);
  }

  return (
    <div className="space-y-4 bg-[#0B1220] p-4 rounded-xl">
      <div className="flex items-center justify-between">
        <div>
          <div className="text-[11px] uppercase tracking-[0.18em] text-gray-400">
            Overview
          </div>
        </div>
        <button
          onClick={() => {
            setShowForm(true);
            setNewInvoice(emptyInvoice(resolvedBusinessId ?? businessId));
            setItems([emptyItem(), emptyItem()]);
          }}
          className="rounded-lg px-4 py-2 text-sm font-semibold border border-[#2DD4BF]/60 text-[#6EF3C5] hover:bg-[#111A2E] hover:border-[#2DD4BF] transition"
          disabled={!resolvedBusinessId}
          type="button"
        >
          + New Smart Invoice
        </button>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
        <div className="rounded-xl border border-[#1E2A44] bg-[#111A2E] p-3">
          <p className="text-xs text-gray-400">Outstanding (Not Paid)</p>
          <p className="mt-1 text-lg font-semibold text-[#6EF3C5]">
            ${outstandingTotal.toLocaleString()}
          </p>
        </div>

        <div className="rounded-xl border border-[#1E2A44] bg-[#111A2E] p-3">
          <p className="text-xs text-gray-400">Overdue</p>
          <p className="mt-1 text-lg font-semibold text-red-400">
            ${overdueTotal.toLocaleString()}
          </p>
        </div>

        <div className="rounded-xl border border-[#1E2A44] bg-[#111A2E] p-3">
          <p className="text-xs text-gray-400">Total Invoices</p>
          <p className="mt-1 text-lg font-semibold text-[#6EF3C5]">
            {invoices.length}
          </p>
        </div>
      </div>

      {!resolvedBusinessId && (
        <p className="text-sm text-red-400">
          Select or create a business first to manage invoices.
        </p>
      )}

      {effectiveError && (
        <div className="rounded-md border border-red-500/40 bg-red-500/10 px-3 py-2 text-sm text-red-200">
          {effectiveError}
        </div>
      )}

      {loading ? (
        <p className="text-sm text-gray-400">Loading invoices...</p>
      ) : invoices.length === 0 ? (
        <p className="text-sm text-gray-400">
          No invoices yet. Click &quot;New Smart Invoice&quot; to create one.
        </p>
      ) : (
        <div className="overflow-x-auto rounded-lg border border-[#1E2A44] bg-[#111A2E]">
          <table className="min-w-full text-sm">
            <thead className="bg-[#0B1220] text-left text-xs font-medium uppercase tracking-wide text-gray-400">
              <tr>
                <th className="px-4 py-3">Invoice #</th>
                <th className="px-4 py-3">Client</th>
                <th className="px-4 py-3">Issue</th>
                <th className="px-4 py-3">Due</th>
                <th className="px-4 py-3">Status</th>
                <th className="px-4 py-3 text-right">Total</th>
                <th className="px-4 py-3 text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-[#1E2A44] bg-[#111A2E] text-gray-200">
              {invoices.map((inv) => {
                const { displayStatus, subtitle } = autoStatusLabel(inv);
                const isMarking = markingId === inv.id;
                const isPaid = inv.status === 'paid';
                const label = isPaid
                  ? 'Paid'
                  : isMarking
                  ? 'Recording...'
                  : 'Mark Paid + Record';
                const hasNotes = !!inv.notes && inv.notes.trim().length > 0;
                const notesOpen = openNotesInvoiceId === inv.id;
                return (
                  <React.Fragment key={inv.id}>
                    <tr>
                      <td className="px-4 py-2 font-medium">
                        {inv.invoice_number}
                      </td>
                      <td className="px-4 py-2 text-gray-200">
                        {inv.client_name}
                      </td>
                      <td className="px-4 py-2 text-gray-300">
                        {inv.issue_date}
                      </td>
                      <td className="px-4 py-2 text-gray-300">
                        {inv.due_date}
                      </td>
                      <td className="px-4 py-2">
                        <div className="flex flex-col gap-0.5">
                          <span
                            className={
                              'inline-flex items-center rounded-full px-2 py-0.5 text-xs font-medium ' +
                              statusBadgeClass(displayStatus)
                            }
                          >
                            {displayStatus.toUpperCase()}
                          </span>
                          {subtitle && (
                            <span className="text-[11px] text-gray-500">
                              {subtitle}
                            </span>
                          )}
                        </div>
                      </td>
                      <td className="px-4 py-2 text-right">
                        ${inv.total.toFixed(2)}
                      </td>
                      <td className="px-4 py-2 text-right space-x-2">
                        <button
                          type="button"
                          onClick={() => handleMarkPaidAndCreateTx(inv)}
                          disabled={isPaid || isMarking}
                          className="rounded-md bg-emerald-600 px-3 py-1 text-[11px] font-semibold text-black hover:bg-emerald-700 disabled:opacity-40"
                        >
                          {label}
                        </button>
                        <button
                          type="button"
                          onClick={() => toggleNotes(inv.id)}
                          disabled={!hasNotes}
                          className={clsx(
                            'rounded-md border px-2 py-1 text-[11px]',
                            hasNotes
                              ? 'border-slate-500 text-slate-200 hover:bg-slate-800'
                              : 'border-slate-700 text-slate-500 cursor-not-allowed'
                          )}
                        >
                          {notesOpen ? 'Hide Notes' : 'Notes'}
                        </button>
                        <select
                          value={inv.status}
                          onChange={(e) =>
                            handleStatusChange(
                              inv,
                              e.target.value as InvoiceStatus
                            )
                          }
                          className="rounded border border-[#1E2A44] bg-[#0B1220] px-2 py-1 text-xs text-gray-200"
                        >
                          <option value="draft">Draft</option>
                          <option value="sent">Sent</option>
                          <option value="paid">Paid</option>
                          <option value="overdue">Overdue</option>
                        </select>

                        {inv.status === 'draft' && (
                          <button
                            type="button"
                            onClick={() => beginEditInvoice(inv)}
                            className="rounded-md border px-2 py-1 text-[11px] border-slate-500 text-slate-200 hover:bg-slate-800 mr-1"
                          >
                            Edit
                          </button>
                        )}

                        <button
                          type="button"
                          onClick={() => handleDownloadInvoice(inv)}
                          className="rounded-md border border-emerald-500/60 px-3 py-1 text-[11px] font-semibold text-emerald-200 hover:bg-emerald-500/10"
                        >
                          Print
                        </button>
                      </td>
                    </tr>
                    {notesOpen && hasNotes && (
                      <tr className="bg-[#111827]">
                        <td colSpan={7} className="px-4 py-3">
                          <div className="text-xs text-gray-200">
                            <div className="font-semibold mb-1">Notes</div>
                            <p className="whitespace-pre-wrap">{inv.notes}</p>
                          </div>
                        </td>
                      </tr>
                    )}
                  </React.Fragment>
                );
              })}
            </tbody>
          </table>
        </div>
      )}

      {showForm && (
        <div className="rounded-lg border border-[#1E2A44] bg-[#111A2E] p-4 space-y-3">
          <div className="flex items-center justify-between">
            <h3 className="text-sm font-semibold text-gray-100">
              New Smart Invoice
            </h3>
            <button
              type="button"
              onClick={() => setShowForm(false)}
              className="text-xs text-gray-400 hover:text-gray-200"
            >
              Close
            </button>
          </div>
          <form onSubmit={handleSaveInvoice} className="space-y-4">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
              <div>
                <label className="block text-xs font-medium text-gray-300">
                  Invoice #
                </label>
                <input
                  type="text"
                  className="mt-1 w-full rounded-md border border-[#1E2A44] bg-[#0B1220] px-2 py-1 text-sm text-gray-200"
                  value={newInvoice.invoice_number ?? ''}
                  onChange={(e) =>
                    handleInvoiceFieldChange('invoice_number', e.target.value)
                  }
                  required
                />
              </div>

              <div>
                <label className="block text-xs font-medium text-gray-300">
                  Client Name
                </label>
                <input
                  type="text"
                  className="mt-1 w-full rounded-md border border-[#1E2A44] bg-[#0B1220] px-2 py-1 text-sm text-gray-200"
                  value={newInvoice.client_name ?? ''}
                  onChange={(e) =>
                    handleInvoiceFieldChange('client_name', e.target.value)
                  }
                  required
                />
              </div>

              <div>
                <label className="block text-xs font-medium text-gray-300">
                  Issue Date
                </label>
                <input
                  type="date"
                  value={newInvoice.issue_date ?? ''}
                  onChange={(e) =>
                    setNewInvoice((prev) => ({
                      ...prev,
                      issue_date: e.target.value === '' ? null : e.target.value,
                    }))
                  }
                  className="mt-1 w-full rounded-md border border-[#1E2A44] bg-[#0B1220] px-2 py-1 text-sm text-gray-200 date-input"
                />
              </div>

              <div>
                <label className="block text-xs font-medium text-gray-300">
                  Due Date
                </label>
                <input
                  type="date"
                  value={newInvoice.due_date ?? ''}
                  onChange={(e) =>
                    setNewInvoice((prev) => ({
                      ...prev,
                      due_date: e.target.value === '' ? null : e.target.value,
                    }))
                  }
                  className="mt-1 w-full rounded-md border border-[#1E2A44] bg-[#0B1220] px-2 py-1 text-sm text-gray-200 date-input"
                />
              </div>
            </div>

      <div className="space-y-2">
              <div className="flex items-center justify-between">
                <p className="text-xs font-medium text-gray-300">Line Items</p>
                <button
                  type="button"
                  onClick={addItemRow}
                  className="text-xs text-gray-400 hover:text-gray-200"
                >
                  + Add Item
                </button>
              </div>
              <div className="overflow-x-auto rounded-md border border-[#1E2A44]">
                <table className="min-w-full text-xs">
                  <thead className="bg-[#0B1220] text-left text-[11px] font-medium text-gray-400">
                    <tr>
                      <th className="px-2 py-2">Description</th>
                      <th className="px-2 py-2 w-24">Qty</th>
                      <th className="px-2 py-2 w-28">Unit Price</th>
                      <th className="px-2 py-2 w-28">Line Total</th>
                      <th className="px-2 py-2 w-10" />
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-[#1E2A44] bg-[#111A2E] text-gray-200">
                    {items.map((item, idx) => {
                      const lineTotal =
                        (item.quantity ?? 0) * (item.unit_price ?? 0);
                      return (
                        <tr key={idx}>
                          <td className="px-2 py-1">
                            <input
                              type="text"
                              className="w-full rounded border border-[#1E2A44] bg-[#0B1220] px-2 py-1 text-xs text-gray-200"
                              placeholder="Service / Item"
                              value={item.description}
                              onChange={(e) =>
                                handleItemChange(
                                  idx,
                                  'description',
                                  e.target.value
                                )
                              }
                            />
                          </td>
                          <td className="px-2 py-1">
                            <input
                              type="number"
                              step="1"
                              inputMode="numeric"
                              placeholder="0"
                              value={item.quantity === null ? '' : item.quantity}
                              onChange={(e) => {
                                const v = e.target.value;
                                handleItemChange(
                                  idx,
                                  'quantity',
                                  v === '' ? null : Number(v)
                                );
                              }}
                              className="w-full rounded border border-[#1E2A44] bg-[#0B1220] px-1 py-1 text-xs text-right text-gray-200"
                            />
                          </td>
                          <td className="px-2 py-1">
                            <input
                              type="number"
                              step="0.01"
                              inputMode="decimal"
                              placeholder="0"
                              value={item.unit_price === null ? '' : item.unit_price}
                              onChange={(e) => {
                                const v = e.target.value;
                                handleItemChange(
                                  idx,
                                  'unit_price',
                                  v === '' ? null : Number(v)
                                );
                              }}
                              className="w-full rounded border border-[#1E2A44] bg-[#0B1220] px-1 py-1 text-xs text-right text-gray-200"
                            />
                          </td>
                          <td className="px-2 py-1 text-right text-xs text-gray-200">
                            ${lineTotal.toFixed(2)}
                          </td>
                          <td className="px-2 py-1 text-center">
                            <button
                              type="button"
                              onClick={() => removeItemRow(idx)}
                              className="text-[11px] text-gray-400 hover:text-red-400"
                            >
                              ✕
                            </button>
                          </td>
                        </tr>
                      );
                    })}
                  </tbody>
                </table>
              </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <label className="block text-xs font-medium text-gray-300">
                  Notes (shown on invoice)
                </label>
                <textarea
                  className="mt-1 w-full rounded-md border border-[#1E2A44] bg-[#0B1220] px-2 py-1 text-sm text-gray-200"
                  rows={3}
                  value={newInvoice.notes ?? ''}
                  onChange={(e) =>
                    handleInvoiceFieldChange('notes', e.target.value)
                  }
                />
              </div>

              <div className="space-y-2">
                <div className="flex justify-between text-sm">
                  <span className="text-gray-400">Subtotal</span>
                  <span className="font-medium text-gray-100">
                    ${Number(newInvoice.subtotal || 0).toFixed(2)}
                  </span>
                </div>
                <div className="flex items-center justify-between gap-2 text-sm">
                  <span className="text-gray-400">Tax</span>
                  <input
                    type="number"
                    step="0.01"
                    inputMode="decimal"
                    placeholder="0"
                    value={newInvoice.tax === null ? '' : newInvoice.tax}
                    onChange={(e) => {
                      const v = e.target.value;
                      setNewInvoice((prev) => {
                        const tax = v === '' ? null : Number(v);
                        const subtotal = Number(prev.subtotal || 0);
                        const total = subtotal + Number(tax || 0);
                        return {
                          ...prev,
                          tax,
                          total,
                        };
                      });
                    }}
                    className="w-32 rounded border border-[#1E2A44] bg-[#0B1220] px-2 py-1 text-right text-xs text-gray-200 tax-input"
                  />
                </div>
                <div className="flex justify-between text-sm">
                  <span className="text-gray-400">Total</span>
                  <span className="text-lg font-semibold text-[#6EF3C5]">
                    ${Number(newInvoice.total || 0).toFixed(2)}
                  </span>
                </div>

                <div className="pt-2">
                  <label className="block text-xs font-medium text-gray-300">
                    Initial Status
                  </label>
                  <select
                    className="mt-1 w-full rounded-md border border-[#1E2A44] bg-[#0B1220] px-2 py-1 text-sm text-gray-200"
                    value={newInvoice.status ?? 'draft'}
                    onChange={(e) =>
                      handleInvoiceFieldChange('status', e.target.value)
                    }
                  >
                    <option value="draft">Draft</option>
                    <option value="sent">Sent</option>
                  </select>
                </div>
              </div>
            </div>

            <div className="flex justify-end gap-2">
              <button
                type="button"
                onClick={() => setShowForm(false)}
                className="rounded-md border border-[#1E2A44] px-3 py-1 text-xs text-gray-300 hover:bg-[#111A2E]"
              >
                Cancel
              </button>
              <button
                type="submit"
            disabled={saving || !resolvedBusinessId}
                className="rounded-md bg-[#2DD4BF] px-4 py-1 text-xs font-semibold text-black hover:bg-[#14B8A6] shadow-md shadow-[#2DD4BF]/30 disabled:opacity-40"
              >
                {saving
                  ? 'Saving…'
                  : editingInvoiceId
                  ? 'Update Invoice'
                  : 'Save Smart Invoice'}
              </button>
            </div>
          </form>
        </div>
      )}

      {/* Hidden printable invoice layouts for PDF export */}
      <div
        id="invoice-print-root"
        style={{
          position: 'fixed',
          left: '-9999px',
          top: 0,
          pointerEvents: 'none',
        }}
      >
        {invoices.map((inv) => (
          <div key={inv.id} id={`invoice-print-${inv.id}`}>
            <InvoicePrintView
              invoice={{
                ...inv,
                items: invoiceItemsById[inv.id] || [],
              }}
            />
          </div>
        ))}
      </div>
    </div>
  );
};

export default InvoiceTab;


